### PR TITLE
Wip:Feature/modules

### PR DESCRIPTION
**Pull request by bielu**
@K3llr as we spoke I am preparing some modules to continue on other projects, I am going to add few more modules there probably, but marking that PR as WIP.
There is examine storage modules, but I remove that from build for now as awaiting Examine 2.0 to more or less be stable enough to continue

### CODE REVIEW

**Comment by bielu** [comment]
@K3llr there are modules ready, there is code for examine provider, but I will have to rethink idea of examine provider, and probably implement directly as repository without abstracting that in that way as done in old stack.

**Comment by K3llr** [comment]
# Changes to Redis components:

**SImpl.Storage.Redis.Module**
- Removed Newtonsoft.Json dependency
- Added IRedisSerializationService
- Added default implementation JsonRedisSerializationService based on System.Text.Json
- Added ability to configure IRedisSerializationService on module
- Deleted RedisDefaultDataGateway
- Changed RedisDataGateway from abstract to concrete
- Moved RedisDataGatewaySettings to SImpl.Storage.KeyValue.Redis

**SImpl.Storage.KeyValue.Redis**
- Renamed RedisDataGatewaySettings to RedisModelStorageStorageSettings
- Added ability to configure model settings
- Configure DI with open generic IRedisKeyValueStorage

**Comment by K3llr** [comment]
Namespaces and classes have been changed thoroughly in SImpl.OAuth and SImpl.Http.OAuth

**Comment by K3llr** [comment]
Didn't touch Simpl.Storage.Examine

**Pull request merged**
